spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:postgresql://localhost:5432/ensaf_ekili
#    username: postgres
#    password: postgres

  datasource:
    type:  com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:ensaf_ekili
    username: sa
    password:

  h2:
    console:
      enabled: true

server:
  error:
    include-stacktrace: always

